services:

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
      RATE_LIMIT_ENABLED: "true"
      REDIS_ENABLED: "true"
      LLM_BACKEND: mock
      LOG_JSON: "true"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app_network


  mongo:
    image: mongo:7
    platform: linux/amd64
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app_network


  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - app_network


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      web:
        condition: service_healthy
    networks:
      - app_network


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: "false"

    secrets:
      - grafana_admin_password
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - app_network


volumes:
  mongo_data:
  redis_data:
  prometheus_data:
  grafana_data:


networks:
  app_network:

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt